name: nextcloud
services:
  nextcloud:
    image: crazymax/nextcloud:latest
    container_name: nextcloud
    depends_on:
      - db
      - msmtpd
      - redis
    environment:
      - APC_SHM_SIZE=128M
      - DB_HOST=nextcloud-db
      - DB_NAME=nextcloud_db
      - DB_PASSWORD=grw5gr4rwRWGwg
      - DB_TYPE=mysql
      - DB_USER=nextcloud_user
      - HSTS_HEADER=max-age=15768000; includeSubDomains
      - LOG_IP_VAR=remote_addr
      - MEMORY_LIMIT=512M
      - OPCACHE_MEM_SIZE=128
      - PGID=1000
      - PUID=1000
      - REAL_IP_FROM=0.0.0.0/32
      - REAL_IP_HEADER=X-Forwarded-For
      - RP_HEADER=strict-origin
      - TZ=Europe/Paris
      - UPLOAD_MAX_SIZE=512M
    healthcheck:
      test: curl -sSf 'http://localhost/status.php' | grep '"installed":true' | grep '"maintenance":false' | grep '"needsDbUpgrade":false' || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - target: 8000
        published: "8337"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/Nextcloud/data
        target: /data
    x-casaos:
      envs: []
    networks:
      - nextcloud
    privileged: false

  cron:
    image: crazymax/nextcloud:latest
    container_name: nextcloud-cron
    depends_on:
      - nextcloud
    environment:
      - APC_SHM_SIZE=128M
      - CRON_PERIOD=*/5 * * * *
      - DB_HOST=nextcloud-db
      - DB_NAME=nextcloud_db
      - DB_PASSWORD=grw5gr4rwRWGwg
      - DB_TYPE=mysql
      - DB_USER=nextcloud_user
      - HSTS_HEADER=max-age=15768000; includeSubDomains
      - LOG_IP_VAR=remote_addr
      - MEMORY_LIMIT=512M
      - OPCACHE_MEM_SIZE=128
      - PGID=1000
      - PUID=1000
      - REAL_IP_FROM=0.0.0.0/32
      - REAL_IP_HEADER=X-Forwarded-For
      - RP_HEADER=strict-origin
      - SIDECAR_CRON=1
      - TZ=Europe/Paris
      - UPLOAD_MAX_SIZE=512M
    restart: unless-stopped
    x-casaos:
      envs: []
    volumes:
      - type: bind
        source: /DATA/AppData/Nextcloud/mysql
        target: /var/lib/mysql
    networks:
      - nextcloud
    privileged: false

  db:
    image: mariadb:10.5
    container_name: nextcloud-db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=nextcloud_db
      - MYSQL_PASSWORD=grw5gr4rwRWGwg
      - MYSQL_USER=nextcloud_user
    restart: unless-stopped
    x-casaos:
      envs: []
    volumes:
      - type: bind
        source: /DATA/AppData/Nextcloud/mysql
        target: /var/lib/mysql
    networks:
      - nextcloud
    privileged: false

  msmtpd:
    image: crazymax/msmtpd:latest
    container_name: nextcloud-msmtpd
    environment:
      - SMTP_AUTH=on
      - SMTP_FROM=foo@gmail.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PASSWORD=bar
      - SMTP_PORT=587
      - SMTP_STARTTLS=on
      - SMTP_TLS=on
      - SMTP_TLS_CHECKCERT=on
      - SMTP_USER=foo
      - TZ=Europe/Paris
    restart: unless-stopped
    x-casaos:
      envs: []
    networks:
      - nextcloud
    privileged: false

  news_updater:
    image: crazymax/nextcloud:latest
    container_name: nextcloud-news-updater
    depends_on:
      - nextcloud
    environment:
      - APC_SHM_SIZE=128M
      - DB_HOST=nextcloud-db
      - DB_NAME=nextcloud_db
      - DB_PASSWORD=grw5gr4rwRWGwg
      - DB_TYPE=mysql
      - DB_USER=nextcloud_user
      - HSTS_HEADER=max-age=15768000; includeSubDomains
      - LOG_IP_VAR=remote_addr
      - MEMORY_LIMIT=512M
      - NC_NEWSUPDATER_INTERVAL=900
      - NC_NEWSUPDATER_LOGLEVEL=error
      - NC_NEWSUPDATER_THREADS=10
      - NC_NEWSUPDATER_TIMEOUT=300
      - OPCACHE_MEM_SIZE=128
      - PGID=1000
      - PUID=1000
      - REAL_IP_FROM=0.0.0.0/32
      - REAL_IP_HEADER=X-Forwarded-For
      - RP_HEADER=strict-origin
      - SIDECAR_NEWSUPDATER=1
      - TZ=Europe/Paris
      - UPLOAD_MAX_SIZE=512M
    restart: unless-stopped
    x-casaos:
      envs: []
    volumes:
      - type: bind
        source: /DATA/AppData/Nextcloud/mysql
        target: /var/lib/mysql
    networks:
      - nextcloud
    privileged: false

  previewgen:
    image: crazymax/nextcloud:latest
    container_name: nextcloud-previewgen
    depends_on:
      - nextcloud
    environment:
      - APC_SHM_SIZE=128M
      - DB_HOST=nextcloud-db
      - DB_NAME=nextcloud_db
      - DB_PASSWORD=grw5gr4rwRWGwg
      - DB_TYPE=mysql
      - DB_USER=nextcloud_user
      - HSTS_HEADER=max-age=15768000; includeSubDomains
      - LOG_IP_VAR=remote_addr
      - MEMORY_LIMIT=512M
      - OPCACHE_MEM_SIZE=128
      - PGID=1000
      - PREVIEWGEN_PERIOD=0 * * * *
      - PUID=1000
      - REAL_IP_FROM=0.0.0.0/32
      - REAL_IP_HEADER=X-Forwarded-For
      - RP_HEADER=strict-origin
      - SIDECAR_PREVIEWGEN=1
      - TZ=Europe/Paris
      - UPLOAD_MAX_SIZE=512M
    restart: unless-stopped
    x-casaos:
      envs: []
    volumes:
      - type: bind
        source: /DATA/AppData/Nextcloud/mysql
        target: /var/lib/mysql
    networks:
      - nextcloud
    privileged: false

  redis:
    image: redis:6-alpine
    container_name: nextcloud-redis
    environment:
      - TZ=Europe/Paris
    restart: unless-stopped
    x-casaos:
      envs: []
    networks:
      - nextcloud
    privileged: false

networks:
  nextcloud:
    name: nextcloud
    
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: nextcloud
  author: crazy-max
  category: TMCstore
  description: 
    en_us: Nextcloud Docker image with advanced features.
  tagline:
    en_us: The productivity platform that keeps you in control
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/nextcloud-icon.png
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/nextcloud-icon.png
  index: /
  port_map: "8337"
  scheme: http
  tips:
    custom: |
      Visit link to finish setup and finetune.
      https://github.com/crazy-max/docker-nextcloud/tree/master#nextcloud
  store_app_id: nextcloud
  title:
    en_us: Nextcloud (Extended)
