name: red-discordbot-shinsekai

services:
  app:
    image: ghcr.io/jclaudan/casaos-tmcstore:red-discordbot-shinsekai-1.0.0
    container_name: red-discordbot-shinsekai
    environment:
      - PREFIX=.
      - PREFIX2=!
      - PUID=1000
      - PGID=1000
      - TOKEN=$DISCORD_TOKEN
      - TZ=Etc/UTC
      - DISPLAY=:99  # Pour les applications graphiques
    volumes:
      - type: bind
        source: /DATA/AppData/Shinsekai-Store/$AppID/data
        target: /data
      - /tmp/.X11-unix:/tmp/.X11-unix  # Nécessaire pour les applications graphiques
    ports:
      - target: 4444
        published: ${PORT_OBS:-10444}
        protocol: tcp
      - target: 5900
        published: ${PORT_VNC:-10900}
        protocol: tcp
      - target: 5900
        published: ${PORT_VNC:-10900}
        protocol: udp
    restart: unless-stopped
    privileged: true

  x-casaos:
    architectures:
      - amd64
      - arm64
      - arm
    category: ShinsekaiStore
    icon: https://cdn.jsdelivr.net/gh/mariosemes/CasaOS-TMCstore@main/Apps/red-discordbot/icon.png
    description:
      en_us: |
        Red is a fully modular bot – meaning all features and commands can be enabled/disabled to your liking, making it completely customizable. This version includes capabilities for streaming video and audio from VLC and a web browser.
    main: app
    port_map: ""
    scheme: http
    tagline:
      en_us: A modular bot with video and audio streaming capabilities from VLC and a web browser.
    store_app_id: red-discordbot-shinsekai
    title:
      en_us: Red Discord Bot with Streaming Capabilities
    screenshot_link:
      - https://cdn.jsdelivr.net/gh/mariosemes/CasaOS-TMCstore@main/Apps/red-discordbot/screenshot-01.png
    thumbnail: https://cdn.jsdelivr.net/gh/mariosemes/CasaOS-TMCstore@main/Apps/red-discordbot/thumbnail.png
