name: ghost
services:
  app:
    container_name: ghost
    hostname: ghost
    depends_on:
      - ghost-db
    environment:
      - NODE_ENV=production
      - database__client=mysql
      - database__connection__host=ghost-db
      - database__connection__user=root
      - database__connection__password=CrazyGoodDatabasePassword1337!
      - database__connection__database=ghost
    image: ghost:latest
    labels:
      icon: https://portainer-io-assets.sfo2.digitaloceanspaces.com/logos/ghost.png
    ports:
      - target: 2368
        published: "2368"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/ghost/content
        target: /var/lib/ghost/content
    networks:
      - ghost
    privileged: false

  ghost-db:
    container_name: ghost-db
    hostname: ghost-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=CrazyGoodDatabasePassword1337!
    image: mysql:8
    labels:
      icon: https://portainer-io-assets.sfo2.digitaloceanspaces.com/logos/ghost.png
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/ghost/mysql
        target: /var/lib/mysql
    networks:
      - ghost
    privileged: false

networks:
  ghost:
    name: ghost

x-casaos:
  author: ghost
  category: TMCstore
  description:
    en_us: Free and open-source blogging platform.
  developer: ""
  icon: https://portainer-io-assets.sfo2.digitaloceanspaces.com/logos/ghost.png
  index: /
  main: app
  port_map: "2368"
  scheme: http
  tagline:
    en_us: Free And Open-source Blogging Platform.
  thumbnail: https://portainer-io-assets.sfo2.digitaloceanspaces.com/logos/ghost.png
  store_app_id: ghost-tmc
  title:
    en_us: Ghost Blogging Platform
