name: chatpadai
services:
  app:
    container_name: chatpadai
    hostname: chatpadai
    image: ghcr.io/deiucanta/chatpad:latest
    labels:
      icon: https://portainer-io-assets.sfo2.digitaloceanspaces.com/logos/chatpadai.png
    ports:
      - target: 80
        published: "8080"
        protocol: tcp
    restart: unless-stopped
    network-mode: bridge
    privileged: false

x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  author: deiucanta
  category: TMCstore
  description:
    en_us: Free and open-source software that provides a user-friendly system for interacting with ChatGPT.
  developer: ""
  icon: https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/ChatGPT_logo.svg/120px-ChatGPT_logo.svg.png
  index: /
  main: app
  port_map: "8080"
  scheme: http
  tagline:
    en_us: Free and open-source software that provides a user-friendly system for interacting with ChatGPT.
  thumbnail: https://github.com/deiucanta/chatpad/raw/main/banner.png
  store_app_id: chatpadai-tmc
  title:
    en_us: chatpadai
