name: red-discordbot-shinsekai

services:
  app:
    image: ghcr.io/jclaudan/casaos-tmcstore:red-discordbot-shinsekai-1.0.0
    container_name: red-discordbot-shinsekai
    environment:
      - PREFIX=.
      - PREFIX2=!
      - PUID=1000
      - PGID=1000
      - TOKEN=$DISCORD_TOKEN
      - TZ=Etc/UTC
      - DISPLAY=:99  # Pour les applications graphiques
    volumes:
      - type: bind
        source: /DATA/AppData/Shinsekai-Store/$AppID/data
        target: /data
      - /tmp/.X11-unix:/tmp/.X11-unix  # Nécessaire pour les applications graphiques
    ports:
      - $PORT_OBS:4444  # Port WebSocket OBS
      - $PORT_VNC:5900  # Port VNC pour contrôler l'environnement graphique
    restart: unless-stopped
    privileged: true
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: User ID under which the bot will run.
        - container: PGID
          description:
            en_us: Group ID under which the bot will run.
        - container: TOKEN
          description:
            en_us: Discord bot token.
        - container: TZ
          description:
            en_us: Time zone of the container.
      ports:
        - container: "4444"
          description:
            en_us: Port for OBS WebSocket.
        - container: "5900"
          description:
            en_us: Port for VNC access to the graphical environment.
      volumes:
        - container: /data
          description:
            en_us: Directory for storing bot data.
      description:
        en_us: |
          Red is a fully modular bot – meaning all features and commands can be enabled/disabled to your liking, making it completely customizable. This version includes capabilities for streaming video and audio from VLC and a web browser.
      architectures:
        - amd64
        - arm64
        - arm
      main: red-discordbot-shinsekai
      author: Your Name or Organization
      category: Multimedia
      icon: https://path/to/your/icon.png
      title:
        en_us: Red Discord Bot with Streaming Capabilities
      tagline:
        en_us: A modular bot with video and audio streaming capabilities from VLC and a web browser.
      thumbnail: https://path/to/your/thumbnail.png

  ffmpeg:
    image: jrottenberg/ffmpeg:4.3-alpine  # Utilisez une version spécifique, pas "latest"
    container_name: ffmpeg
    command: ["-loglevel", "debug", "-i", "input", "-c:v", "libx264", "-f", "flv", "output"]
    volumes:
      - /DATA/AppData/Shinsekai-Store/$AppID/data_ffmpeg:/data
    restart: unless-stopped

x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  author: red-discordbot
  category: ShinsekaiStore
  description:
    en_us: Red is a fully modular bot – meaning all features and commands can be enabled/disabled to your liking, making it completely customizable. This version includes capabilities for streaming video and audio from VLC and a web browser.
  developer: Your Name or Organization
  icon: https://cdn.jsdelivr.net/gh/jclaudan/CasaOS-TMCstore@main/Apps/red-discordbot/icon.png
  index: /
  main: app
  scheme: http
  port_map: "4444"
  tagline:
    en_us: A modular bot with video and audio streaming capabilities from VLC and a web browser.
  title:
    en_us: Red Discord Bot with Streaming Capabilities
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/jclaudan/CasaOS-TMCstore@main/Apps/red-discordbot/screenshot-01.png
  thumbnail: https://path/to/your/thumbnail.png


